services:
    redis:
        image: redis:7.2.4
        container_name: redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - real-time-chat-network

    mongodb:
        image: mongo:7.0.9
        container_name: mongodb
        ports:
            - "27017:27017"
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 40s
        networks:
            - real-time-chat-network

    aysncq-webui:
        image: hibiken/asynqmon:latest
        entrypoint: ["/asynqmon", "--redis-addr=redis:6379"]
        restart: "always"
        ports:
            - 8585:8080
        depends_on:
            redis:
                condition: service_healthy

    auth_api:
        image: auth_api:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: auth_api
        ports:
            - 3000:3000
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - real-time-chat-network

    room_api:
        image: room_api:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: room_api
        ports:
            - 3001:3001
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - real-time-chat-network

    message_api:
        image: message_api:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: message_api
        ports:
            - 3002:3002
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - real-time-chat-network

    auth_api_grpc:
        image: auth_api_grpc:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: auth_api_grpc
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - real-time-chat-network

    message_task_server:
        image: message_task_server:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: message_task_server
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        networks:
            - real-time-chat-network

networks:
    real-time-chat-network:
        driver: bridge
# TODO setup vloum
